### PR TITLE
Import changes from Xenial up to version 229-4ubuntu21.28

### PR DESCRIPTION
**Pull request by peat-psuwit**
This PR brings the changes from Ubuntu 16.04 up to version 229-4ubuntu21.22.

Wait, doesn't Ubuntu Touch still run Upstart? Well, systemd is far wider than an init system and includes an essential component (udev) for the system [1]. Besides, some other packages are still installed in the rootfs.

Some of the imported releases are security releases, however, not all of them are related to the components Ubuntu Touch uses. I personally think it's still better to import all of them, as it'll be easier to import those that are related to us in the future.

I also improve our patch a bit by fixing memory leak and improve error handling.

This has been tested on FP2 Halium 7.1 port, E4.5, MX4, M10 FHD, and Pinephone.

[1] P.S.: I personally don't like it when systemd subsumes Linux base components like that, but meh.

### CODE REVIEW

**Comment by UniversalSuperBox** [comment]
This build failure is reproducible only on systems running the version of pbuilder on xenial. An upgrade to pbuilder or our entire build setup may be required.

**Comment by peat-psuwit** [comment]
Now that our CI is fixed, I've imported additional versions since the first import.

@UniversalSuperBox do we want a full all-devices test?

**Review by UniversalSuperBox — APPROVED** [review]
We unfortunately haven't seen much testing from the community. However, I've tested the following on the Nexus 5, Nexus 4, Xperia X, FairPhone 2, Oneplus One, and Nexus 7 (where applicable):

* GPS
* Accelerometer
* Camera
* Bluetooth
* Media output
* SMS
* Phone calls
* Timezones (Setting and rebooting to check if they're still set)

With all this done, I believe this is safe to merge.

**Comment by UniversalSuperBox** [comment]
QA Notes:

This PR caused https://github.com/ubports/ubuntu-touch/issues/1585, which was later fixed by https://github.com/ubports/systemd-packaging/pull/2. We have not noticed any new problems since then.

**Pull request merged**
